# (https://gohugo.io/hosting-and-deployment/hosting-on-netlify/#configure-hugo-version-in-netlify)

# Default build settings
[build]
  # publish = "website/public"
  command = "git submodule update -f --init && hugo --themesDir themes/"

# "production" environment specific build settings
[build.environment]
  HUGO_VERSION = "0.64.1"
  HUGO_THEME = "zdoc"
  HUGO_ENV = "production"